IS_FRACTION:
    PUSH(IMM(3));
    CALL(MALLOC);
    DROP(1);
    MOV(IND(R0), T_CLOSURE);
    MOV(INDD(R0,1),10004);
    MOV(INDD(R0,2),LABEL(IS_FRACTION_CODE));
    JUMP(IS_FRACTION_EXIT);
    
IS_FRACTION_CODE:
//  printf("### in label: IS_FRACTION_CODE \n");
//  printf("Arg = %lu\n",STARG(2));
    MOV(R0,STARG(2));
    PUSH(IMM(R0));
    CALL(IS_SOB_FRACTION);
    DROP(1);
    CMP(R0, IMM(0));
    JUMP_EQ(IS_FRACTION_FALSE);
    MOV(R0, SOB_TRUE);
    JUMP(IS_FRACTION_EXIT);

IS_FRACTION_FALSE:
    MOV(R0, SOB_FALSE);

IS_FRACTION_EXIT:
    RETURN;