IS_SYMBOL:
    PUSH(IMM(3));
    CALL(MALLOC);
    DROP(1);
    MOV(IND(R0), T_CLOSURE);
    MOV(INDD(R0,1),10009);
    MOV(INDD(R0,2),LABEL(IS_SYMBOL_CODE));
    JUMP(IS_SYMBOL_EXIT);
    
IS_SYMBOL_CODE:
//  printf("### in label: IS_SYMBOL_CODE \n");
//  printf("Arg = %lu\n",STARG(2));
    MOV(R0,STARG(2));
    PUSH(IMM(R0));
    CALL(IS_SOB_SYMBOL);
    DROP(1);
    CMP(R0, IMM(0));
    JUMP_EQ(IS_SYMBOL_FALSE);
    MOV(R0, IMM(SOB_TRUE));
    JUMP(IS_SYMBOL_EXIT);

IS_SYMBOL_FALSE:
    MOV(R0, IMM(SOB_FALSE));

IS_SYMBOL_EXIT:
    RETURN;